/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dat250assignment1;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

public class UnitConverterTest {

    private static final double TOLERANCE = 0.0001; // A small tolerance for double comparisons

    @Test
    public void testConvertInchesToFeet() {
        Converter converter = new Converter();
        double result = converter.convert("in", "ft", 12.0); // 12 inches = 1 foot
        assertEquals(1.0, result, TOLERANCE);
    }

    @Test
    public void testConvertMetersToMiles() {
        Converter converter = new Converter();
        double result = converter.convert("m", "mi", 1609.344); // 1609.344 meters = 1 mile
        assertEquals(1.0, result, TOLERANCE);
    }

    @Test
    public void testConvertInvalidUnits() {
        Converter converter = new Converter();
        double result = converter.convert("invalid", "ft", 10.0); // Invalid 'from' unit
        assertTrue(Double.isNaN(result)); // Expect result to be NaN

        result = converter.convert("ft", "invalid", 10.0); // Invalid 'to' unit
        assertTrue(Double.isNaN(result)); // Expect result to be NaN
    }

    @Test
    public void testConvertSameUnits() {
        Converter converter = new Converter();
        double result = converter.convert("in", "in", 5.0); // Converting to the same unit should return the same value
        assertEquals(5.0, result, TOLERANCE);
    }

    @Test
    public void testConvertZeroValue() {
        Converter converter = new Converter();
        double result = converter.convert("mi", "ft", 0.0); // Converting 0 miles to feet should be 0
        assertEquals(0.0, result, TOLERANCE);
    }
}
